temp:
  #开启动态移除温控
  dynamic: true
  #温度墙 电池温度如果高于此值关闭快充 450 = 45.0度
  max: 450
  #最大充电电流
  speed: "300000000"
  #进行替换的温控配置文件
  file: [
    "thermal-4k.conf",
    "thermal-arvr.conf",
    "thermal-camera.conf",
    "thermal-class0.conf",
    "thermal-hp-mgame.conf",
    "thermal-hp-normal.conf",
    "thermal-mgame.conf",
    "thermal-navigation.conf",
    "thermal-nolimits.conf",
    "thermal-normal.conf",
    "thermal-per-camera.conf",
    "thermal-per-class0.conf",
    "thermal-per-navigation.conf",
    "thermal-per-normal.conf",
    "thermal-per-video.conf",
    "thermal-phone.conf",
    "thermal-tgame.conf",
    "thermal-video.conf",
    "thermal-videochat.conf",
  ]

#每轮监听间隔时长 过短会导致功耗增加 单位:秒
sleep: 60
#顾名思义
debug: false
#进行替换的温控配置文件
configfile: "/data/adb/modules/acceleratedcharging/config/normal.conf"